/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjPersonalBrandRouteImport } from './routes/tj-personal-brand'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as MonthlyTargetsRouteImport } from './routes/monthly-targets'
import { Route as MmContentRouteImport } from './routes/mm-content'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DataEntryRouteImport } from './routes/data-entry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ActionablesRouteImport } from './routes/actionables'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsTargetsRouteImport } from './routes/settings.targets'
import { Route as SettingsExportRouteImport } from './routes/settings.export'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'

const TjPersonalBrandRoute = TjPersonalBrandRouteImport.update({
  id: '/tj-personal-brand',
  path: '/tj-personal-brand',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyTargetsRoute = MonthlyTargetsRouteImport.update({
  id: '/monthly-targets',
  path: '/monthly-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const MmContentRoute = MmContentRouteImport.update({
  id: '/mm-content',
  path: '/mm-content',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntryRoute = DataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionablesRoute = ActionablesRouteImport.update({
  id: '/actionables',
  path: '/actionables',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTargetsRoute = SettingsTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/actionables': typeof ActionablesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data-entry': typeof DataEntryRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/mm-content': typeof MmContentRoute
  '/monthly-targets': typeof MonthlyTargetsRoute
  '/processes': typeof ProcessesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tj-personal-brand': typeof TjPersonalBrandRoute
  '/clients/$id': typeof ClientsIdRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/actionables': typeof ActionablesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data-entry': typeof DataEntryRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/mm-content': typeof MmContentRoute
  '/monthly-targets': typeof MonthlyTargetsRoute
  '/processes': typeof ProcessesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tj-personal-brand': typeof TjPersonalBrandRoute
  '/clients/$id': typeof ClientsIdRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/actionables': typeof ActionablesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data-entry': typeof DataEntryRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/mm-content': typeof MmContentRoute
  '/monthly-targets': typeof MonthlyTargetsRoute
  '/processes': typeof ProcessesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tj-personal-brand': typeof TjPersonalBrandRoute
  '/clients/$id': typeof ClientsIdRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/actionables'
    | '/clients'
    | '/dashboard'
    | '/data-entry'
    | '/finance'
    | '/login'
    | '/mm-content'
    | '/monthly-targets'
    | '/processes'
    | '/sales'
    | '/settings'
    | '/tj-personal-brand'
    | '/clients/$id'
    | '/settings/export'
    | '/settings/targets'
    | '/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/actionables'
    | '/clients'
    | '/dashboard'
    | '/data-entry'
    | '/finance'
    | '/login'
    | '/mm-content'
    | '/monthly-targets'
    | '/processes'
    | '/sales'
    | '/settings'
    | '/tj-personal-brand'
    | '/clients/$id'
    | '/settings/export'
    | '/settings/targets'
    | '/settings/team'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/actionables'
    | '/clients'
    | '/dashboard'
    | '/data-entry'
    | '/finance'
    | '/login'
    | '/mm-content'
    | '/monthly-targets'
    | '/processes'
    | '/sales'
    | '/settings'
    | '/tj-personal-brand'
    | '/clients/$id'
    | '/settings/export'
    | '/settings/targets'
    | '/settings/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ActionablesRoute: typeof ActionablesRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DataEntryRoute: typeof DataEntryRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  MmContentRoute: typeof MmContentRoute
  MonthlyTargetsRoute: typeof MonthlyTargetsRoute
  ProcessesRoute: typeof ProcessesRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TjPersonalBrandRoute: typeof TjPersonalBrandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tj-personal-brand': {
      id: '/tj-personal-brand'
      path: '/tj-personal-brand'
      fullPath: '/tj-personal-brand'
      preLoaderRoute: typeof TjPersonalBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-targets': {
      id: '/monthly-targets'
      path: '/monthly-targets'
      fullPath: '/monthly-targets'
      preLoaderRoute: typeof MonthlyTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mm-content': {
      id: '/mm-content'
      path: '/mm-content'
      fullPath: '/mm-content'
      preLoaderRoute: typeof MmContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-entry': {
      id: '/data-entry'
      path: '/data-entry'
      fullPath: '/data-entry'
      preLoaderRoute: typeof DataEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actionables': {
      id: '/actionables'
      path: '/actionables'
      fullPath: '/actionables'
      preLoaderRoute: typeof ActionablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/targets': {
      id: '/settings/targets'
      path: '/targets'
      fullPath: '/settings/targets'
      preLoaderRoute: typeof SettingsTargetsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface SettingsRouteChildren {
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsTargetsRoute: typeof SettingsTargetsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsExportRoute: SettingsExportRoute,
  SettingsTargetsRoute: SettingsTargetsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ActionablesRoute: ActionablesRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DataEntryRoute: DataEntryRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  MmContentRoute: MmContentRoute,
  MonthlyTargetsRoute: MonthlyTargetsRoute,
  ProcessesRoute: ProcessesRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TjPersonalBrandRoute: TjPersonalBrandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
